### ISSUE TITLE
Briefing

### ISSUE THREAD

**Issue by paulojunior95** [admissoesevida/admv#1]
Esta issue serve para planejar as features e características do site.

**Comment by paulojunior95** [comment]
Sugestão da Aline: inicio, sobre, departamentos (com informacoes de cada departamento), blog (pagina para posts de mensagens e testemunhos), contato (admvbauru@gmail.com, Rua Primeiro de Agosto, 7-78, Centro, Bauru - SP)... e colocar link das redes sociais (Facebook: ADMISSOESEVIDABAURU, Youtube: Missões e Vida Assembleia de Deus)

**Comment by paulojunior95** [comment]
Penso no site como uma pagina para publicação de fotos, eventos e datas... mas também um lugar pra membros poderem acessar o sistema da igreja. Assim o site seria só a capinha do sistema.

**Comment by paulojunior95** [comment]
Sugestão do @eltonmiranda15, local para navegar pela bíblia no site.
Já encontramos o conteúdo da bíblia pra aplicação, em 3 versões e 2 idiomas([biblia](../../biblia) e [bible](../../bible)).

**Comment by paulojunior95** [comment]
Outras sugestões de tópicos

- Multimidia (fotos, videos)
- Conteúdos (textos)
- Agenda de eventos
- Link para o portal interno de membros (outro site)
- Contato com endereço e maps

Painel de controle
- Tela simplificada onde o administrador consegue visualizar, editar e gerenciar todos os conteúdos disponíveis no site.
- Utilizaremos popups para edição, evitando a mudança de janela (estilo SPA)
- Sugestão utilizar Angular, React, Vue ou algum outro framework javascript.

**Comment by paulojunior95** [comment]
@eltonmiranda15 pode fazer uma análise SEO para nós.

**Comment by paulojunior95** [comment]
Modelo de site de igreja
https://youtu.be/zYXEDYVlhbM

**Comment by paulojunior95** [comment]
Foi criado um repositório para armazenar os fluxogramas do projeto: [admissoesevida/fluxograms](https://github.com/admissoesevida/fluxograms).
Acredito que assim seja mais facil projetar e organizar as ideias.

**Comment by Alinecrisfran** [comment]
Podemos utilizar a [API da Bíblia](https://docs.api.bible/docs/overview) ao invés de utilizar a bíblia local.
